### ISSUE TITLE
Add 'sensors' and 'RTC' modules

### ISSUE THREAD

**Issue by ladyada** [adafruit/adafruit-raspberrypi-linux#2]
http://forums.adafruit.com/viewtopic.php?f=50&t=31821

**Comment by pdp7** [comment]
Based on bootc.net's Wheezy image, these are the modules needed for DS1307 RTC and TMP102 temp sensor:

tmp102
hwmon
rtc_ds1307

Gallery of screenshots: https://picasaweb.google.com/117542001281850354871/AdafruitOccidentalisV01I2CIssue#

thanks,
drew

**Comment by pdp7** [comment]
Thanks!  I saw:

https://github.com/adafruit/adafruit-raspberrypi-linux/commit/264be1a955ae4a4d1053e5bafc160ff0bfaa8f7d

Is there somewhere to download new compiled kernel for Occidentalis?

**Comment by ladyada** [comment]
Please be patient, we are still working! Releases will be announced on the Adafruit Blog for those who do not want to compile their own kernels :)

**Comment by pdp7** [comment]
Y'all really do take Friday Piday seriously :)  I just saw Occidentalist v0.2 and the RTC tutorial.  I look forward to trying it out tonight.  Interesting to see how you left off the one resistor to make it safe without level shifter.  Thanks!

**Comment by pdp7** [comment]
fyi - tmp102 working good:

root@raspberrypi:~# modprobe tmp102
root@raspberrypi:~# lsmod
Module                  Size  Used by
tmp102                  3558  0 
hwmon                   1977  1 tmp102
rtc_ds1307              7602  0 
i2c_dev                 6423  0 
snd_bcm2835            21781  0 
snd_pcm                87261  1 snd_bcm2835
snd_seq                67042  0 
snd_timer              21734  2 snd_seq,snd_pcm
snd_seq_device          6928  1 snd_seq
snd                    61480  5 snd_seq_device,snd_timer,snd_seq,snd_pcm,snd_bcm2835
snd_page_alloc          5411  1 snd_pcm
spidev                  5600  0 
evdev                   9780  0 
spi_bcm2708             5386  0 
rpi_pwm                 7203  0 
i2c_bcm2708             3834  0 
root@raspberrypi:~# echo tmp102 0x48 > /sys/class/i2c-adapter/i2c-0/new_device
root@raspberrypi:~# sensors
tmp102-i2c-0-48
Adapter: bcm2708_i2c.0
temp1:        +26.6°C  (high = +160.0°C, hyst = +150.0°C)
