### ISSUE TITLE
fbtft_device fails to load with 3.15.8+ and 2.8" PiTFT TS

### ISSUE THREAD

**Issue by sarnold** [adafruit/adafruit-raspberrypi-linux#5]
Have the current PiTFT 2.8" module from Adafruit but it doesn't work with 3.15 branch (and the patch available for download from Adafruit fails on "matching" mainline).  The raspbian 3.12 kernel works as documented with both raspbian and Gentoo (but only using the 3.12 raspbian kernel).  Tried building my own 3.15 w/ several configs (including using your config from the firmware repo) and also tried using your 3.15 image and they all fail the same way.  I've already made some Adafruit kernel source packages for Gentoo and once it works I'll add an Adafruit kernel recipe to my yocto meta-raspberrypi fork.  Can you point to a commit in the adafruit-rpi-fbtft repo that you think might work?  Or maybe a commit for a 3.12 branch?  What's the current plan for bumping from 3.10 as default?

Thanks in advance...

**Comment by sarnold** [comment]
Turns out the defconfig has a couple of modules that should be builtins instead, then 3.15 works as expected, more or less.  I'd recommend updating the adafruit_defconfig and changing these to "y":

CONFIG_DMA_BCM2708=y
CONFIG_DMA_VIRTUAL_CHANNELS=y﻿

**Comment by ladyada** [comment]
sorry just closing this now, we're now on 3.18 which has fbtft in staging :)
