### ISSUE TITLE
PiTFT 3.5" (hx8357d) does not show up as /dev/fb0

### ISSUE THREAD

**Issue by yann-morin-1998** [adafruit/adafruit-raspberrypi-linux#8]
Hello!

The PiTFT35R_raspbian image provided in the "easy install" procedure
is working "OK" (in that the TFT panel properly display the console and the
X desktop when manually started).

However, recompiling the kernel manually (for another system running a
Buildroot-based system), the fbtft_device modules complains about the
"adafruitrt35" being unknown; and indeed it is nowhere to be found in
the source tree.

I've tried various changesets, even from before the migration to the drivers
in staging, and the source for fbtft_device never ever mentioned the
"adafruitrt35" variant... :-(

So, I've tried to load fbtft_device with those options:

```
custom=1 name=adafruitrt35 rotate=90 frequency=32000000
```

But to no avail. :-( I've tried various combinarions, including specifying
the gpios=dc:25  but that wsa not workign either...

Would it be possible that you update the source for fbtft_device with the
details for that display, please?

Regards,
Yann E. MORIN.

**Comment by toddtreece** [comment]
@yann-morin-1998 this is now handled by device tree overlays in 3.18.y. you can find them here: https://github.com/adafruit/Adafruit-Pi-Kernel-o-Matic/tree/pitft

**Comment by yann-morin-1998** [comment]
@toddtreece Huho, great! Closing, then. Thanks! :-)
